### ISSUE TITLE
possible to add `--onion` to enable only onions and disable non onions?

### ISSUE THREAD

**Issue by nyxnor** [Kicksecure/repository-dist#1]
Only problem I see is with fastrack not having that and in the meantime a workaround could be done.
Later would be great for it to also take care of debian.list and qubes-r4.list.

**Comment by adrelanos** [comment]
Not really using the github issue tracker. If you don't mind, please move to Whonix forums as per https://www.whonix.org/wiki/Reporting_Bugs#Issue_Tracker

Otherwise if you prefer here, could also stay here since you're contributing a lot to Whonix.

Created https://forums.whonix.org/t/tool-to-onionize-all-apt-sources/13367 for it where I'll answer soon.

**Comment by nyxnor** [comment]
wherever it is more organized.
